### ISSUE TITLE
feature: have an indicator to know when the plugin is enabled

### ISSUE THREAD

**Issue by farzadmf** [dmtrKovalenko/caps-word.nvim#1]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Hi, first of all, thank you for the very useful plugin (I'm surprised why you didn't receive more stars, since I personally find this very useful)

One limitation I find is that I cannot know when the plugin is enabled/disabled until I type something.

### Describe the solution you'd like

I was thinking of:
- Maybe have an option to enable a notification being displayed when the plugin is toggled.
- And possibly having a `lualine` integration

### Describe alternatives you've considered

Nothing that I can think of

**Comment by dmtrKovalenko** [comment]
nice thank you for using it 

I've been thinking about something like this but lualine integration might be complicated to do but I can definitely add a hook for sending notification on enter/exit

**Comment by farzadmf** [comment]
Thank you @dmtrKovalenko ; this will be very useful, and thank you for the quick turnaround
